DESC EMP
DESC DEPT
DESC SALGRADE

SELECT ENAME, JOB, MGR, HIREDATE, SAL + NVL(COMM, 0), DEPTNO FROM EMP;
SELECT * FROM DEPT;
SELECT * FROM SALGRADE;


/*
SELECT
	A.EMPNO, A.ENAME, B.ENAME MGR,  A.HIREDATE, A.DEPTNO, D.DNAME
FROM
	EMP A JOIN DEPT D
	ON
	A.DEPTNO = D.DEPTNO JOIN EMP B ON
	A.MGR = B.EMPNO;
*/

------------------------------
SELECT 
	AVG(SAL + NVL(COMM, 0)) SAL_MEDIU
	FROM 
	EMP
	WHERE
	DEPTNO = (
			SELECT DEPTNO
			FROM
			DEPT
			WHERE
			DNAME LIKE 'RESEARCH');

-------------------------------

SELECT
	A.ENAME NUME_ANGAJAT,
	D.DNAME DENUMIRE_DEPARTAMENT,
	EXTRACT(MONTH FROM A.HIREDATE) LUNA_ANGAJARE,
	DECODE(SIGN(EXTRACT(YEAR FROM A.HIREDATE) - 1980), 1, 'NOU', 'VECHI') APRECIERE_VECHIME
FROM
	EMP A JOIN DEPT D ON
	A.DEPTNO = D.DEPTNO
WHERE
	A.SAL > (
			SELECT 
			AVG(SAL)
			FROM 
			EMP
			WHERE
			DEPTNO = (
					SELECT DEPTNO
					FROM
					DEPT
					WHERE
					DNAME LIKE 'RESEARCH')
			)
AND
	EXTRACT(YEAR FROM A.HIREDATE) = 
	(
		SELECT EXTRACT(YEAR FROM HIREDATE)
		FROM
		EMP
		GROUP BY
		EXTRACT(YEAR FROM HIREDATE)
		HAVING COUNT(*) = (SELECT MAX(COUNT(*))
				FROM
				EMP
				GROUP BY
				EXTRACT(YEAR FROM HIREDATE)
				)
	);


