DESC EMP
DESC DEPT

/*
SUBCERERI

-----------------------------------
PE CLAUZA WHERE
-----------------------------------

SA SE SELECTEZE PT FIECAREA ANGAJAT CARE CASTIGA MAI MULT DECAT ALEN
SI NU FACE PARTE DIN DEPT SALES, NUMELE, SI VENITUL SAU
*/

SELECT A.ENAME, A.SAL + NVL(A.COMM, 0) VENIT 
FROM EMP A
WHERE
A.DEPTNO != (SELECT DEPTNO
				FROM DEPT
				WHERE 
				DNAME = 'SALES')
AND
A.SAL + NVL(A.COMM, 0) > (SELECT SAL + NVL(COMM,0)
							FROM EMP
							WHERE
							ENAME = 'ALEN');
/*
IN PARANTEZE, 
SE PUN IN PARTEA DREAPTA A CONDITITEI,
SUBCERERI NECORELATE (NU DEPIND DE CEREREA PRINCIPALA)

MAI INTAI SE EXECUTA SUBCEREREILE DUPA CEREREA PRINCIPALA

NU E VOIE ORDER BY IN SUBCERERE
MERGE GRUP BY
*/

/*

SA SE SELECTEZE PT FIECARE ANGAJAT CE CASTIGA MAI MULT 
DECAT MEDIE PE INTREAGA FIRMA, NUMELE, NUMELE SEFULUI,
CAT CASTIGA EL (VENIT)

*/
/*
SELECT A.ENAME. B.ENAME, A.SAL
FROM EMP A JOIN EMP B
	ON A.MGR = B.EMPNO
WHERE
A.SAL > (SELECT AVG(SAL) FROM EMP);
*/

/*

FOLOSIND DOAR SUBCERERI SA SE SELECTEZE ANGAJATUL DIN DEPT SALES
CARE ARE CEL MAI MARE SAL DIN ACEST DEPT

*/

-- NU MERGE
SELECT A.ENAME, A.SAL
FROM EMP A
WHERE A.DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME = 'SALES')
AND
A.SAL = (SELECT MAX(SAL) FROM EMP);

/* 
SA SE AFISEZE TOTI ANGAZATII CARE SUNT IN GRADUL SALARIAL GRAD 2
CARE SUNT IN DEPT LUI BLAKE SAU AL LUI MARTIN
*/

SELECT A.ENAME, B.GRADE
FROM EMP A JOIN SALGRADE B
	ON A.SAL BETWEEN B.LOSAL AND B.HISAL
WHERE
	B.GRADE = 2
	AND
	A.DEPTNO IN(SELECT DEPTNO FROM EMP WHERE ENAME IN ('BLAKE', 'MARTIN'));

/*
SA SE AFISEZE PT FIECARE ANGAJAT CARE NU FACE PARTE DIN SALES
SI CARE CASTIGA MAI MULT DECAT MEDIA VENITULUI DIN DEPT SAU
NUMELE SI VENITUL
*/

--CORELATE

SELECT A.ENAME, A.SAL + NVL(A.COMM, 0) VENIT
FROM EMP A
WHERE 
A.DEPTNO != (SELECT DEPTNO
			FROM DEPT
			WHERE
			DNAME = 'SALES')
AND
A.SAL + NVL(A.COMM, 0) > (SELECT AVG(B.SAL + NVL(B.COMM, 0))
							FROM EMP B
							WHERE
							B.DEPTNO = A.DEPTNO);
-- PRIMUL SAL
SELECT A.ENAME, A.SAL
FROM EMP A
WHERE
	A.SAL = (SELECT MAX(SAL) FROM EMP);

-- AL 2LEA SALARIU
SELECT A.ENAME, A.SAL
FROM EMP A
WHERE
	A.SAL = (SELECT MAX(SAL) FROM EMP
			WHERE
				SAL != (SELECT MAX(SAL) FROM EMP));

-- AL 4LEA
SELECT A.ENAME, A.SAL
FROM EMP A
WHERE
	3 = (SELECT COUNT(DISTINCT B.SAL)
		FROM EMP B
		WHERE
			B.SAL > A.SAL);

-- PRIMII 4 (DISTINCTE)
SELECT A.ENAME, A.SAL
FROM EMP A
WHERE
	4 > (SELECT COUNT(DISTINCT B.SAL)
		FROM EMP B
		WHERE
			B.SAL > A.SAL);

----------------------------------
-- SUBCERERE IN FROM
----------------------------------

/*

LA FIECARE ANGAJAT CARE CASTIGA MAI PUTIN DECAT SEFUL LUI
NUMELE LUI, NUMELE SEFULUI, DIFERENTA INTRE CELE 2 VENITURI 
SALARIUL MEDIU PE COMPANIE

*/

SELECT A.ENAME, B.ENAME, 
B.SAL + NVL(B.COMM, 0) - A.SAL - NVL(A.COMM, 0) DIF, AVGS.MEDIE
FROM EMP A JOIN EMP B 
	ON A.MGR = B.EMPNO, (SELECT AVG(SAL) MEDIE FROM EMP) AVGS
WHERE A.SAL + NVL(A.COMM, 0) < B.SAL + NVL(B.COMM, 0);

/*
SA SE SELETEZE PT FIECARE ANGAJAT CARE CASTIGA MAI MULT DECAT BLAKE
(VENIT) NUMELE, SALARIUL ANGAJATULUI, SAL LUI BLAKE SI DENUMIREA DEPT LUI
BLAKE -- IN SUBCERERE IN CLAUZA FROM
*/

SELECT A.ENAME, A.SAL, BLAKE.SAL, BLAKE.DNAME
FROM EMP A, (SELECT B.SAL, C.DNAME, B.COMM
				FROM EMP B JOIN DEPT C
					ON B.DEPTNO = C.DEPTNO
				WHERE B.ENAME = 'BLAKE') 
			BLAKE
WHERE
	A.SAL + NVL(A.COMM, 0) > BLAKE.SAL + NVL(BLAKE.COMM, 0);


----------------- TEST ------------------

/*

SA SE AFISEZE TOTI ANGAJATII DEPARTAMENTELOR
RESEARCH SAU SALES
CARE S-AU ANGAJAT IN LUNA DIFERITA CU SEFUL LOR DIRECT
INDIFERENT DE AN
AFISAND PT FIECARE ANG NUMEEL ANG, NUMELE SEFULUI, DATA DE ANGAJARE
PT ANGAJAT. DATA DE ANGAJARE PT SEF SI DENUMIRE DEPT PT ANGAJAT

2 METODE DISTINCTE

*/

-- 1
SELECT A.ENAME, S.ENAME, A.HIREDATE, S.HIREDATE, D.DNAME
FROM EMP A, EMP S, DEPT D
WHERE
	A.MGR = S.EMPNO
AND 
	A.DEPTNO = D.DEPTNO
AND
	D.DNAME IN('SALES', 'RESEARCH')
AND
	EXTRACT(MONTH FROM A.HIREDATE) != EXTRACT(MONTH FROM S.HIREDATE);

-- 2

SELECT A.ENAME, S.ENAME, A.HIREDATE, S.HIREDATE, C.DNAME
FROM EMP A, EMP S, DEPT C
WHERE A.MGR = S.EMPNO
	AND 
	A.DEPTNO = C.DEPTNO 
	AND
	A.DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME = 'SALES' OR DNAME = 'RESEARCH')
	AND 
	EXTRACT(MONTH FROM A.HIREDATE) != EXTRACT(MONTH FROM S.HIREDATE);
