DESC EMP
DESC DEPT
DESC BONUS
DESC SALGRADE

-- 1
SELECT ENAME, SAL
FROM EMP A, DEPT B
WHERE
	A.DEPTNO = B.DEPTNO
	AND
	A.SAL > 2000;

-- JOIN
/*
-- MERGE CU ORICATE, DAR TREBUIE LEGATE
SELECT A.ENAME, A.SAL
FROM EMP A JOIN
	DEPT B
	ON A.DEPTNO = B.DEPTNO, SALGRADE S
	WHERE
		<<CONDITIE JOIN>>
*/

-- 2
-- ECHIVALENT CU 1
SELECT A.ENAME, A.SAL
FROM EMP A JOIN
	DEPT B
	ON A.DEPTNO = B.DEPTNO
	WHERE
		A.SAL > 2000;

-- 3
-- CAND COLOANELE SUNT NUMITE LA FEL (DEPTNO IN CAZUL ASTA)
SELECT A.ENAME, A.SAL
	FROM EMP A JOIN DEPT B
	USING(DEPTNO)
	WHERE
		A.SAL > 2000;

-- 4
-- NATURAL JOIN
SELECT A.ENAME, A.SAL
	FROM EMP A NATURAL JOIN DEPT B
	WHERE
		A.SAL > 2000;

-- NU E VOIE A.DEPTNO SAU B.DEPTNO
-- FARA ALIASURI PT COLOANE NUMITE LA FEL

-- PRIN CELE 4 METODE, TOTI ANGAJATII
-- CARE AU VENIT IN FIRMA DUPA 1 DEC 1982
-- SI CARE NU FAC PARTE DIN DEPT RESEARCH

SELECT A.ENAME, A.SAL
FROM EMP A, DEPT B
WHERE
	A.DEPTNO = B.DEPTNO
	AND
		HIREDATE > TO_DATE('01-12-1982','DD-MM-YYYY')
	AND
		B.DNAME != 'RESEARCH';

SELECT A.ENAME, A.SAL
FROM EMP A JOIN DEPT B
	ON A.DEPTNO = B.DEPTNO
	WHERE
		HIREDATE > TO_DATE('01-12-1982','DD-MM-YYYY')
	AND
		B.DNAME != 'RESEARCH';

SELECT A.ENAME, A.SAL
	FROM EMP A JOIN DEPT B
		USING(DEPTNO)
	WHERE
		HIREDATE > TO_DATE('01-12-1982','DD-MM-YYYY')
	AND
		B.DNAME != 'RESEARCH';

SELECT A.ENAME, A.SAL
	FROM EMP A NATURAL JOIN DEPT B
	WHERE
		HIREDATE > TO_DATE('01-12-1982','DD-MM-YYYY')
	AND
		B.DNAME != 'RESEARCH';


--JOIN DIN ACEIASI TABELA
SELECT A.ENAME, A.SAL, S.ENAME, S.SAL
	FROM EMP A, EMP S
	WHERE 
		A.MGR = S.EMPNO
	AND
		A.SAL > S.SAL;

SELECT A.ENAME, A.SAL, S.ENAME, S.SAL
	FROM EMP A JOIN EMP S
		ON A.MGR = S.EMPNO
	WHERE
		A.SAL > S.SAL;

SELECT A.ENAME, A.SAL, S.ENAME, S.SAL, K.ENAME, K.SAL
	FROM EMP A, EMP S, EMP K
	WHERE 
		A.MGR = S.EMPNO
	AND
		A.SAL > S.SAL
	AND
		K.MGR IS NULL;

SELECT A.ENAME, A.SAL, S.ENAME, S.SAL, K.ENAME
	FROM EMP A JOIN EMP S
		ON A.MGR = S.EMPNO, EMP K
	WHERE
		A.SAL > S.SAL
	AND
		K.MGR IS NULL;

SELECT A.ENAME, A.SAL, S.GRADE
	FROM EMP A, SALGRADE S
	WHERE
		A.SAL >= S.LOSAL
	AND
		A.SAL <= S.HISAL;
-- ECHIVALENT CU BETWEEN S.LOSAL AND S.HISAL

SELECT  A.ENAME, A.SAL, S.GRADE
	FROM EMP A JOIN
		SALGRADE S
	ON A.SAL BETWEEN S.LOSAL AND S.HISAL;

--SELECT ENAME, SAL
--	FROM EMP;

-- TOTI ANGAJATII DIN DEP RESEARCH CU SAL > 2000
SELECT A.ENAME, A.SAL
	FROM EMP A
	WHERE
		A.SAL > 2000
UNION
SELECT B.ENAME, NVL(B.COMM, 0)
	FROM EMP B NATURAL JOIN DEPT C
	WHERE
		C.DNAME = 'RESEARCH'
ORDER BY 2;


-- SA SE SELECTEZE TOTI ANGAJATII CARE NU IL AU SEF
-- PE JONES SI CARE FAC PARTE DINTR-UN DEP CITIT DE LA TASTATURA,
-- AFISAND NUME, DEN DEP, NUME SEF
-- IN 3 MODURI / 

SELECT A.ENAME, C.DNAME, B.ENAME SEF
	 FROM EMP A, EMP B, DEPT C
	 WHERE
	 	A.MGR = B.EMPNO
	 AND
	 	A.DEPTNO = C.DEPTNO
	 AND
	 	B.ENAME != 'JONES'
	 AND
	 	C.DNAME = '&DEPARTAMENT';

SELECT A.ENAME, C.DNAME, B.ENAME SEF
	FROM EMP A JOIN
		EMP B
	ON A.MGR = B.EMPNO, DEPT C
	WHERE
		A.DEPTNO = C.DEPTNO
 	AND
	 	B.ENAME != 'JONES'
	AND
	 	C.DNAME = '&&DEPARTAMENT2';

UNDEFINE DEPARTAMENT2

ACCEPT DEPARTAMENT3 CHAR PROMPT "DEPARTAMENT3: "
SELECT A.ENAME, C.DNAME, B.ENAME SEF
	FROM EMP A JOIN DEPT C
		USING(DEPTNO), EMP B
	WHERE
		A.MGR = B.EMPNO
 	AND
	 	B.ENAME != 'JONES'
	AND
	 	C.DNAME = '&&DEPARTAMENT3';