/*
COMM
*/
CREATE TABLE DEPART(
	COD_DEPART NUMBER(2),
	DEN_DEPART VARCHAR2(20),
	NR_ANGAJAM NUMBER(2),
	CONSTRAINT PK_DEPART PRIMARY KEY(COD_DEPART)
	);
	DESC DEPART

CREATE TABLE ANGAJATI(
	COD_DEPART NUMBER(2),
	COD_ANGAJAT NUMBER(3),
	NUME VARCHAR2(10),
	PRENUME VARCHAR2(10),
	NUME_SEF VARCHAR2(10),
	SALARIU NUMBER(7,2),
	LOCALITATE VARCHAR2(20),
	CONSTRAINT PK_ANGAJAT
	PRIMARY KEY (COD_DEPART, COD_ANGAJAT),
	CONSTRAINT FK_ANGAJATI_DEPART
	FOREIGN KEY(COD_DEPART)
	REFERENCES DEPART(COD_DEPART)
	);
	DESC ANGAJATI

INSERT INTO DEPART VALUES (1, 'IT', 6);
INSERT INTO DEPART VALUES (2, 'HR', 10);
INSERT INTO ANGAJATI
VALUES (1, 1, 'RADU', 'NICOLAE', 'POP ION', 3400, 'BUCURESTI');
INSERT INTO ANGAJATI 
VALUES (1, 2, 'VLAD', 'MIHAI', 'POP ION', 3100, 'BUCURESTI');
INSERT INTO ANGAJATI 
VALUES (1, 3, 'RADU', 'CRISTIAN', 'POP ION', 2800, 'CRAIOVA');
INSERT INTO ANGAJATI 
VALUES (2, 1, 'TEMNEANU', 'MARIA', 'TRANCA DAN', 2200, 'BUCURESTI');
INSERT INTO ANGAJATI 
VALUES (2, 2, 'HRISTOS', 'IISUS', 'TRANCA DAN', 1900, 'SIBIU');
INSERT INTO ANGAJATI 
VALUES (2, 3, 'TIMOFTE', 'MARIUS', 'DANIEL ANA', 2000, 'BRASOV');

--ACCEPT LOC CHAR PROMPT 'Introdu localitate: '
DEFINE LOC='BUCURESTI'
DEFINE SAL=2800

SELECT NUME, PRENUME, SALARIU
FROM ANGAJATI
WHERE
	SALARIU > &&SAL
	AND
	LOCALITATE != '&&LOC'
ORDER BY SALARIU DESC, NUME;

SELECT NUME, PRENUME, SALARIU
FROM ANGAJATI
WHERE
	SALARIU = &SAL
	AND
	LOCALITATE != '&LOC';

/*
SELECT 'ANGAJATUL ' ||NUME||
	' CASTIGA ' ||SALARIU
FROM ANGAJATI;
*/

-- DEZLEAGA VARIABILA DE VALOARE
UNDEFINE SAL
UNDEFINE LOC
-- DEFINE VAR=/VALOARE/ PT LEGARE

-- ========= 1 ==========

/*
SA SE SELECTEZE TOTI ANGAJATII CARE AU UN SEF CITIT DE LA TASTATURA
SI AU UN DEPARTAMENT CU CODUL CITIT DE LA TASTATURA
AFISAND NUME, PRENUME, NUME_SEF
REZULTATE SORTATE DUPA SALARIU SI DUPA NUME CRESCATOR
VETI FACE PRIN 3 FELURI

1. DOAR 1&
2. 2 && CU UNDEFINE
3. DEFINE ACCEPT

*/

SELECT NUME, PRENUME, NUME_SEF
FROM ANGAJATI
WHERE
	NUME_SEF = '&NS'
	AND
	COD_DEPART = &CD
ORDER BY SALARIU ASC, NUME ASC;

-- ========== 2 =========

SELECT NUME, PRENUME, NUME_SEF
FROM ANGAJATI
WHERE
	NUME_SEF = '&&NS'
	AND
	COD_DEPART = &&CD
ORDER BY SALARIU ASC, NUME ASC;

UNDEFINE NS
UNDEFINE CD

-- ======= 3 =======

DEFINE NS='POP ION'
ACCEPT CD CHAR PROMPT 'Introduceti codul departamentului: '


SELECT NUME, PRENUME, NUME_SEF
FROM ANGAJATI
WHERE
	NUME_SEF = '&&NS'
	AND
	COD_DEPART = &&CD
ORDER BY SALARIU ASC, NUME ASC;

UNDEFINE NS
UNDEFINE CD

DROP TABLE ANGAJATI;
DROP TABLE DEPART;