--C:\Users\naume\OneDrive\Desktop\Facultate\BD\laborator4.txt
DESC DEPT;
DESC EMP;

-- VARIANTA 1
SELECT ENAME, SAL, COMM
FROM EMP
WHERE
	SAL > 100
	AND
	(COMM IS NULL
	OR
	COMM = 0);

-- VARIANTA 2
/*
CREATE TABLE VENITURI AS
SELECT ENAME, SAL, COMM
FROM EMP
WHERE
	SAL > 100
	AND
	NVL(COMM, 0) = 0;
-- DACA COMM NU E NULL -> COMM
-- ALTFEL -> 0
DROP TABLE VENITURI;
*/

-- VENIT = SAL + NVL(COMM, 0)
SELECT ENAME, SAL + NVL(COMM, 0) VENIT
FROM EMP
WHERE
	SAL > 100
	AND
	NVL(COMM, 0) = 0;


-- TOTI ANGAJATII CU JOB CITIT DE LA TASTATURA
-- SI SALARIU <= 1000 

/*
CREATE TABLE COPIE AS
SELECT ENAME, JOB, SAL + NVL(COMM, 0) VENIT
FROM EMP
WHERE
	JOB = '&JB'
	AND
	SAL <= 1000;
DESC COPIE;

UNDEFINE JB
DROP TABLE COPIE;
*/

-- VAR 1
SELECT ENAME, HIREDATE
FROM EMP
WHERE
	HIREDATE >= TO_DATE('01-01-1981','DD-MM-YYYY')
	AND
	HIREDATE <= TO_DATE('31-12-1981','DD-MM-YYYY');

-- VAR 2
SELECT ENAME, HIREDATE
FROM EMP
WHERE
	HIREDATE BETWEEN TO_DATE('01-01-1981','DD-MM-YYYY')
						AND
					TO_DATE('31-12-1981','DD-MM-YYYY');

-- VAR 3
SELECT ENAME, HIREDATE
FROM EMP
WHERE
	TO_CHAR(HIREDATE,'YYYYMMDD') 
	BETWEEN '19810101' AND '19811231';

-- VAR 4
SELECT ENAME, HIREDATE
FROM EMP
WHERE
	TO_CHAR(HIREDATE,'YYYY') = '1981';

-- TOTI ANGAJATII CARE AU NUMELE INCEPAND CU O LITERA
SELECT ENAME
FROM EMP
WHERE
	ENAME LIKE 'A%';
	-- DACA SCRIAM = 'A%' -> LITERAR A%
	-- '_A%' -> A 2A LITERA A
	-- '%A%' -> LITERA A IN INTERIRO

-- SA SE SLECTEZE TOTI ANGAJATII CARE
-- AU VENIT IN FIMRA INAINTE DE O DATA CITITA DE LA TASTATURA
-- CARE AU UN SALARIU < DECAT O VAL CITITA DE LA TASTATURA
-- NU AU COMISION
-- NU AU JOBUL MANAGER

-- NUME, JOB, HIREDATE, COMM
-- 3 FELURI DIFERITE  MINIM 2 DIFERENTEI INTRE METODE

-- 1 
SELECT ENAME, JOB, HIREDATE, COMM
FROM EMP
WHERE
	SAL < &&SALARIU
	AND
	TO_CHAR(HIREDATE,'YYYYMMDD') < '&&DATA'
	AND
	(COMM IS NULL
		OR
	COMM = 0)
	AND
	JOB != 'MANAGER';

UNDEFINE SALARIU
UNDEFINE DATA

-- 2
ACCEPT DATA CHAR PROMPT 'Introduceti data in format DD-MM-YYYY: '
SELECT ENAME, JOB, HIREDATE, COMM
FROM EMP
WHERE
	SAL < &SALARIU
	AND 
	HIREDATE <= TO_DATE('&&DATA','DD-MM-YYYY')
	AND
	(COMM IS NULL
		OR
	COMM = 0)
	AND
	JOB != 'MANAGER';


UNDEFINE DATA

-- 3
ACCEPT SALARIU CHAR PROMPT 'Introduceti valoare salariu: '
ACCEPT DATA1 CHAR PROMPT 'Introduceti data in format DD-MM-YYYY: '
SELECT ENAME, JOB, HIREDATE, COMM
FROM EMP
WHERE
	SAL < &&SALARIU
	AND 
	(HIREDATE BETWEEN TO_DATE('01-01-1900','DD-MM-YYYY')
		AND
	  TO_DATE('&&DATA1','DD-MM-YYYY'))
	AND
	NVL(COMM, 0) = 0
	AND
	JOB != 'MANAGER';

UNDEFINE SALARIU
UNDEFINE DATA1