DESC EMP
DESC DEPT
DESC SALGRADE


SELECT ENAME, DEPTNO, HIREDATE FROM EMP;
SELECT * FROM DEPT;
SELECT * FROM SALGRADE;

-- GRADUL LUI KING
SELECT 
	B.GRADE
FROM
	SALGRADE B JOIN EMP KING ON
		KING.SAL BETWEEN B.LOSAL AND B.HISAL
WHERE
	KING.ENAME LIKE 'KING';

-- DEPARTAMENTUL CU CEI MAI MULTI ANGAJATI
SELECT
	DEPTNO
FROM
	EMP
GROUP BY
	DEPTNO
HAVING 
	COUNT(*) = 	(
				SELECT
					MAX(COUNT(*))
				FROM
					EMP
				GROUP BY
					DEPTNO
				);

-- ANGAJATI CU DEPARTAMENT
SELECT
	A.ENAME, A.HIREDAT, A.DEPTNO, D.DNAME
FROM
	EMP A JOIN DEPT D
	ON
	A.DEPTNO = D.DEPTNO;
												

/*
PENTRU TOTI ANG DIN DEPT CU CEI MAI PUTINI ANG,
ANGAJATI CARE NU FAC PARTE DIN GRADUL SALARIAL AL LUI KING
SA SE AFISEZE NUMELE ANGAJATULUI, DENUMIREA DEPT, GRADUL SAL
SI O APRECIERE A SALARIULUI ASTFEL, 
DACA SAL > 3000 SCRIEM BUN, DACA <= 3000 BUNICEL
*/

--SELECT "--------------- AICI -----------------------";

SELECT 
	A.ENAME NUME,
	D.DNAME DEPARTAMENT,
	G.GRADE GRAD,
	DECODE(SIGN(A.SAL - 3000), 1, 'BUN', 'BUNICEL') APRECIERE
FROM
	EMP A JOIN DEPT D ON
		A.DEPTNO = D.DEPTNO
	JOIN SALGRADE G ON
		A.SAL BETWEEN G.LOSAL AND G.HISAL
WHERE
	G.GRADE NOT IN 	(
					SELECT 
						B.GRADE
					FROM
						SALGRADE B JOIN EMP KING ON
							KING.SAL BETWEEN B.LOSAL AND B.HISAL
					WHERE
						KING.ENAME LIKE 'KING'
					)
AND
	D.DNAME = 	(
				SELECT
					C.DNAME
				FROM
					DEPT C JOIN EMP I ON
						C.DEPTNO = I.DEPTNO
					GROUP BY 
						C.DNAME
					HAVING 
						COUNT(*) =
							(
							SELECT
								MIN(COUNT(*))
							FROM
								EMP
							GROUP BY
								DEPTNO
							)
				);



SELECT 
	A.ENAME, D.DNAME, G.GRADE, 
	DECODE(SIGN(A.SAL - 3000), 1, 'BUN', 'BUNICEL') APRECIERE
FROM
	EMP A JOIN DEPT D ON 
		A.DEPTNO = D.DEPTNO 
	JOIN SALGRADE G ON
		A.SAL BETWEEN G.LOSAL AND G.HISAL
WHERE
	G.GRADE IN (
				SELECT 
					B.GRADE
				FROM 
					SALGRADE B JOIN EMP C ON
						C.SAL BETWEEN B.LOSAL AND B.HISAL
				GROUP BY B.GRADE
				HAVING COUNT(*) = 
					(
					SELECT 
						MAX(COUNT(*)) 
					FROM 
						EMP JOIN SALGRADE ON 
							SAL BETWEEN LOSAL AND HISAL
					GROUP BY GRADE
					)
				)
AND
	A.DEPTNO != (
				SELECT 
					DEPTNO
				FROM
					EMP
				WHERE
					ENAME LIKE 'KING'
				);



/*
SA SE SCRIE O CERERE SQL CARE FACE O LISTA CU DEPARTAMENTUL IN CARE S-AU FACUT CELE
MAI MULTE ANGAJARI INTR-UN AN. LISTA VA CONTINE DENUMIREA DE DEPARTAMENT, 
ANUL IN CARE S-AU FACUT CELE MAI MULTE ANGAJARI IN DEPARTAMENTUL RESPECTIV 
SI NUMARUL DE ANGAJARI
ANTET: 	
	DEN_DEPT	AN  	NR_ANG
*/


SELECT 
	A.DNAME 								DEN_DEPT, 
	EXTRACT(YEAR FROM B.HIREDATE) 			AN, 
	COUNT(*) 								NR_ANG
FROM 
	EMP B JOIN DEPT A 
	ON 
	B.DEPTNO = A.DEPTNO
GROUP BY 
	A.DNAME, 
	EXTRACT(YEAR FROM B.HIREDATE)
HAVING 
	COUNT(*) = (
				SELECT
					MAX(COUNT(*))
				FROM
					EMP C
				GROUP BY 
					C.DEPTNO,
					EXTRACT(YEAR FROM C.HIREDATE)
				);

	------------------------------------------

/*
ANGAJATII CARE S-AU ANGAJAT IN FIRMA DUPA BLAKE
SI
AU VENITUL MAI MIC DECAT VENITUL MEDIU DIN DEPARTAMENTUL
CU CEI MAI MULTI ANGAJATI
SA SE AFISEZE NUMELE ANG, DEN DEPT, VENITUL SI ANUL ANGAJARII
*/

SELECT 
	A.ENAME 							Nume_angajat,
	B.DNAME 							Denumire_departament,
	A.SAL + NVL(A.COMM, 0) 				Venit,
	EXTRACT(YEAR FROM A.HIREDATE) 		Anul_angajarii
FROM 
	EMP A JOIN DEPT B
	ON 
	A.DEPTNO = B.DEPTNO
WHERE
	A.HIREDATE > 	(
					SELECT 
						HIREDATE 
					FROM
						EMP
					WHERE
						ENAME LIKE 'BLAKE'
					)
AND
	A.SAL + NVL(A.COMM, 0) < 	(
								SELECT 
									AVG(SAL + NVL(COMM, 0))
								FROM 
									EMP
								WHERE
									DEPTNO = 	(
												SELECT
													DEPTNO
												FROM
													EMP
												GROUP BY
													DEPTNO
												HAVING 
													COUNT(*) = 	(
																SELECT
																	MAX(COUNT(*))
																FROM
																	EMP
																GROUP BY
																	DEPTNO
																)
												)
								);

	----------------------
	/*

SA SE CREEZE O TABELA NUMITA ANGAJATI_ALLEN CONTINAD PRIMII 2
ANGAJATI CA MARIME A VENITURILOR LOR CE FAC PARTE DIN ACELASI
GRAD SALARIAL CU ALLEN
VETI AFISA
NUME ANGAJAT, VENIT, GRAD SALARIAL
INCLUDE SI SELECTAREA INREGISTRARILOR DIN TABELA SI STERGEREA TABELEI

*/

CREATE TABLE ANGAJATI_ALLEN
AS
SELECT 
	A.ENAME, A.SAL + NVL(A.COMM, 0) VENIT, C.GRADE
FROM
	EMP A JOIN SALGRADE C
	ON
	A.SAL BETWEEN C.LOSAL AND C.HISAL
WHERE
	C.GRADE = 	(
				SELECT
					B.GRADE
				FROM 
					SALGRADE B JOIN EMP AN ON
						AN.SAL BETWEEN B.LOSAL AND B.HISAL
				WHERE
					AN.ENAME LIKE 'ALLEN'
				)
ORDER BY -2
FETCH FIRST 2 ROWS ONLY;

DESC ANGAJATI_ALLEN

SELECT * FROM ANGAJATI_ALLEN; 

DROP TABLE ANGAJATI_ALLEN;